# Generated by Django 4.2.23 on 2025-08-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='TypeEngin',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='type_engin',
        ),
        migrations.RenameField(
            model_name='typeengin',
            old_name='name',
            new_name='nom_type_engin',
        ),
        migrations.RenameField(
            model_name='typeengin',
            old_name='price',
            new_name='prix',
        ),
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('POS', 'Point of Sale'), ('WEB', 'Web'), ('OTHER', 'Autre')], default='WEB', max_length=10),
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_vendeur', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeurs', to='sales.zone')),
            ],
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='sales.vendeur')),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.vendeur'),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
