# Generated by Django 5.2 on 2025-05-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_vendeur_alter_sale_seller_delete_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendeur',
            old_name='nom_de_vente',
            new_name='nom_du_vendeur',
        ),
    ]
