# Generated by Django 5.2 on 2025-05-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_nom_de_vente_vendeur_nom_du_vendeur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='name',
            new_name='nom_produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='produit',
        ),
    ]
