# Generated by Django 5.2 on 2025-05-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_product_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='user',
        ),
    ]
