# Generated by Django 5.2 on 2025-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
