# Generated by Django 5.2 on 2025-06-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_pos_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='source',
            field=models.CharField(choices=[('POS', 'Point of Sale'), ('WEB', 'Web'), ('OTHER', 'Autre')], default='WEB', max_length=10),
        ),
    ]
