# Generated by Django 5.2 on 2025-06-17
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0008_sale_source'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='Sexe',
        ),
    ]
