# Generated by Django 5.2 on 2025-06-22 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_vendeur_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pos',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='pos',
            name='is_connected',
        ),
        migrations.AddField(
            model_name='pos',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='sales.vendeur'),
        ),
    ]
